schemaVersion: 2.3.0
metadata:
  generateName: fraud-detection
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      image: tiangolo/python-machine-learning:python3.6-tensorflow
      memoryRequest: 1Gi
      memoryLimit: 8Gi
      cpuLimit: '4'
      cpuRequest: '0.5'
