schemaVersion: 2.3.0
metadata:
  generateName: fraud-detection
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      image: quay.io/opendatahub/workbench-images:cuda-jupyter-tensorflow-ubi9-python-3.9-20240718
      memoryRequest: 1Gi
      memoryLimit: 10Gi
      cpuLimit: '4'
      cpuRequest: '0.5'
